# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Animations Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/0.45.0/Configuring/Animations/ 

animations {
    enabled = true
    bezier = overshot, 0.13, 0.99, 0.29, 1.1
    bezier = b0, 0, 1, 0, 1.025
    bezier = b1, 0, 1.1, 0, 1.05
    #animation = layers, 1, 4, b0, popin
    animation = borderangle, 0
    animation = border, 0, 5, default
    animation = windows, 1, 4, b1, slide
    animation = windowsIn, 1, 4, b0, popin 70%
    animation = windowsOut, 1, 4, b0, slide
    animation = windowsMove, 1, 4, default
    animation = workspaces, 1, 3, default, slide
}
