# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Animations Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/0.45.0/Configuring/Animations/ 

animations {
    enabled = true
    bezier = overshot, 0.13, 0.99, 0.29, 1.1
    bezier = b0, 0, 1, 0, 1.025
    bezier = b1, 0, 1.1, 0, 1.05
    bezier = overshot2, 0.18, 0.95, 0.22, 1.03
    bezier = overshot3, 0.18, 0.95, 0.22, 1
    bezier = wind, 0.12, 0.92, 0.08, 1.0
    bezier = liner, 1, 1, 1, 1
    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    bezier = easeOutQuad, 0.25, 0.46, 0.45, 0.94
    bezier = spring, 0.18, 0.89, 0.32, 1.28

    #animation = borderangle, 1, 24, liner, loop
    animation = border, 1, 10, default
    animation = windows, 1, 2, spring, popin 90%
    animation = windowsIn, 1, 4, overshot2, gnomed 
    animation = windowsOut, 1, 4, overshot2, slide
    animation = windowsMove, 1, 6, overshot3 
    animation = workspaces, 1, 5, overshot2, slidefade 30%

    #animation = layers, 1, 4, default, popin
    animation = fadeIn, 1, 7, default
    animation = fadeOut, 1, 7, default
    animation = fadeSwitch, 1, 7, default
    animation = fadeShadow, 1, 7, default
    animation = fadeDim, 1, 7, default
    animation = fadeLayers, 1, 7, default
}
