
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$filemanager = kitty -e yazi &
#$applauncher = rofi -show drun -sort
$applauncher = nc -U /run/user/1000/walker/walker.sock
$terminal = kitty 
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'
$capturing = screenshot
$browser = zen-browser &
$browserClass = zen
$configPath = ~/.config/hypr
