# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

env = HYPRCURSOR_THEME,Future-black-cursors
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,capitaine-cursors
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = GTK_THEME,adw-gtk3:dark
env = GTK2_RC_FILES,/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc

env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
env = XDG_MENU_PREFIX,arch-

env = ROFI, $HOME/.config/rofi/script.sh
