plugin {
    hyprbars {
        bar_height = 20
        bar_color = rgb(1e1e1e)
        bar_title_enabled = false
        bar_button_padding = 10
        bar_padding = 10
        bar_precedence_over_border = true
        hyprbars-button = $red, 15, X, hyprctl dispatch killactive
        hyprbars-button = $yellow, 15, , hyprctl dispatch fullscreen 2
        hyprbars-button = $green, 15, , hyprctl dispatch togglefloating
   }

   hyprexpo {
        columns = 3
        gap_size = 15
        bg_col = rgb(111111)
        workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1

        gesture_distance = 300 # how far is the "max" for the gesture
	skip_empty = true
    }

    hyprfocus {
	enabled = yes
 	animate_floating = yes
    	animate_workspacechange = no
    	focus_animation = shrink
    	bezier = smoothOut, 0.36, 0, 0.66, -0.56
    	bezier = smoothIn, 0.25, 1, 0.5, 1
    	bezier = realsmooth, 0.28, 0.29, 0.69, 1.08
    	bezier = easeInOutBack, 0.68, -0.6, 0.32, 1.6

	flash {
      		flash_opacity = 0.7
      		in_bezier = smoothIn
      		in_speed = 0.5
      		out_bezier = smoothOut
      		out_speed = 3
    	}

	shrink {
      		shrink_percentage = 0.998
      		in_bezier = b1
      		in_speed = 1
      		out_bezier = b1
      		out_speed = 3
    	}
    } 
}
