# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Startup Apps                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/Configuring/Keywords/ 

# Execute your favorite apps at launch

# Services
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#exec-once = wl-paste --type text --watch cliphist store # Stores only text data
#exec-once = wl-paste --type image --watch cliphist store # Stores only image data
#exec-once = cliphist wipe # clear clipboard on startup
exec-once = copyq --start-server

exec = hypridle
exec-once = hyprpm reload

exec-once = hypridle & hyprpaper & waybar & 

#exec-once = systemctl --user import-environment &
#exec-once = hash dbus-update-activation-environment 2>/dev/null &
#exec-once = dbus-update-activation-environment --systemd &

# Apps
exec-once = xfce4-power-manager
exec-once = nm-applet --indicator &
exec-once = steam-native -silent & com.spotify.Client & tuxedo-control-center --tray &
exec-once = swaync &

# General
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"
exec = hyprctl setcursor capitaine-cursors 26
