# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Startup Apps                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Services
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = copyq --start-server

exec = hypridle
exec-once = hyprpm reload

exec-once = hypridle & hyprpaper & waybar & 

# Apps
exec-once = xfce4-power-manager
exec-once = nm-applet --indicator &
exec-once = steam-native -silent & com.spotify.Client & tuxedo-control-center --tray &
exec-once = swaync &

# General
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"
exec = hyprctl setcursor capitaine-cursors 26
