# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Windowrules Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# General window rules
windowrule = idle_inhibit fullscreen
windowrule = float on, match:class ^(LibreWolf)$, match:title ^(Picture-in-Picture)$
windowrule = render_unfocused on, match:class .*(steam_app_|wine|proton|lutris|heroic).*  
windowrule = min_size 1 1, match:xwayland true 
windowrule = stay_focused on, dim_around on, match:class ^(polkit-gnome-authentication-agent-1|com.github.hluk.copyq)$

# Title based rules 
windowrule = float on, match:title ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp|\
                                    .*Discord|(?i).*rename.*|(?i).*save.*|(?i).*open.*|\
                                    (?i).*setting.*|Better Control|Picture-in-Picture|\
                                    Open File|Save File|Steam - Self Updater)$

windowrule = center on, match:title ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp|Discord|\
                                    (?i).*rename.*|(?i).*save.*|(?i).*open.*|(?i).*setting.*|Better Control|Picture-in-Picture)$
 
windowrule = size (monitor_w*0.65) (monitor_h*0.65), match:title ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp|\
                                                                  (?i).*rename.*|(?i).*save.*|(?i).*open.*|Better Control)$

windowrule = size (monitor_w*0.8) (monitor_h*0.8), match:title ^(.*Discord)$

# Class based rules
windowrule = float on, match:class ^(7zFM|org.pulseaudio.pavucontrol|com.github.hluk.copyq\
                                    xdg-desktop-portal-gtk.*|xdg-desktop-portal-kde.*|xdg-desktop-portal-hyprland.*)$

windowrule = center on, match:class ^(xdg-desktop-portal-gtk|com.github.hluk.copyq)$
windowrule = size (monitor_w*0.4) (monitor_h*0.4), match:class ^(com.github.hluk.copyq|xdg-desktop-portal-gtk)$

# Layers Rules #
layerrule = animation slide top, match:namespace logout_dialog
layerrule = animation slide down, blur on, ignore_alpha 0, match:namespace waybar
layerrule = animation fade 50%, match:namespace wallpaper
layerrule = blur on, dim_around on, animation popin 97%, ignore_alpha 0, match:namespace rofi

layerrule = dim_around on, blur on, ignore_alpha 0, match:namespace swaync-control-center
layerrule = ignore_alpha 0.3, match:namespace swaync-notification-window
layerrule = blur on, match:namespace swaync-notification-window

# smart gaps
workspace = f[1], gapsout:1, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
